@startuml
hide footbox
skinparam ArrowFontStyle normal

participant ":ScheduleCommand" as ScheduleCommand
participant "students:StudentList" as StudentList
participant "targetStudent:Student" as Student
participant "newLesson:Lesson" as Lesson
participant "ui:Ui" as Ui

[-> ScheduleCommand : execute(students, ui)
activate ScheduleCommand

ScheduleCommand -> StudentList : getActiveStudent(studentIndex - 1)
activate StudentList
StudentList --> ScheduleCommand : targetStudent
deactivate StudentList

create Lesson
ScheduleCommand -> Lesson : Lesson(day, startTime, endTime)
activate Lesson
Lesson --> ScheduleCommand : newLesson
deactivate Lesson

ScheduleCommand -> Student : addLesson(newLesson)
activate Student
deactivate Student

ScheduleCommand -> Student : getName()
activate Student
Student --> ScheduleCommand : name
deactivate Student

ScheduleCommand -> Ui : showLessonScheduled(name, newLesson)
activate Ui
deactivate Ui

[<-- ScheduleCommand
deactivate ScheduleCommand
destroy ScheduleCommand
@enduml